### ISSUE TITLE
キリ番

### ISSUE THREAD

**Issue by opera7133** [opera7133/opera7133#1]

**Comment by yayoimizuha** [comment]
![image](https://user-images.githubusercontent.com/32425706/90526779-c3de3b80-e1ab-11ea-8481-def90f28ce2f.png)

**Comment by opera7133** [comment]
ありがとうございます！！

**Comment by opera7133** [comment]
あーあ (´△｀)
![スクリーンショット 2020-10-02 223918](https://user-images.githubusercontent.com/39876629/94929510-2727f100-0500-11eb-9bc8-5c7ae074fa5f.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/54709302/95670405-4e985100-0bc5-11eb-9dd6-91935f13d20d.png)

**Comment by opera7133** [comment]
うれしい :)
